apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/customer1/
patches:
  - target:
      kind: SecretProviderClass
      name: customer1-secrets
    patch: |-
      - op: replace
        path: /spec/parameters/userAssignedIdentityID
        value: "8a427fda-65f7-4eea-8f17-d9a9597ab72c"
      - op: replace
        path: /spec/parameters/tenantId
        value: "3af986a9-762c-4c6c-91bb-7ab4916cb7d0"
  - target:
      kind: ObjectStore
      name: customer1-objectstore
    patch: |-
      - op: replace
        path: /spec/configuration/destinationPath
        value: "https://mercurybackupsfredlc.blob.core.windows.net/customer1"
